### ISSUE TITLE
Normalization using own parameters

### ISSUE THREAD

**Issue by ymkng** [ArnaudDroitLab/metagene2#20]
Hi,

I was wondering if there is an option for metagene2 where I can normalize with "RPM" but using my own input parameters (not the same as read counts from the input bam file)?

best,

Michelle Kang

**Comment by ericfournier2** [comment]
Hello Michelle,

I'm afraid we don't have anything of the sort. You would have to deal with raw data and do some post-processing on your own. What are those external parameters you want to normalize over? Per-sample spike-in counts?

Cheers,
-Eric

**Comment by ericfournier2** [comment]
Closing for now, feel free to reopen with further details.
