### ISSUE TITLE
Cannot group bam files for all transcripts

### ISSUE THREAD

**Issue by lundlab-kaltinel** [ArnaudDroitLab/metagene2#25]
Hi, 
I am trying to plot a metagene for all CDSs merged for each transcript, and shown in the same graph.
With the examples in vignette, I can plot all bam file coverage separetely for for ex. list 1 and list2 in GRangesList object, after stiching the regions together. The example I made is for ENST00000000412.
![11](https://user-images.githubusercontent.com/47667755/70137080-79ed0e00-168d-11ea-8f46-1453cbb2c43d.png)

Is it possible to make one plot out of all entries in the GRangesList object ( in this case, all transcripts, not only one/two), plotted as one?
Thank you.

**Comment by ericfournier2** [comment]
Hello, could you share the code you're using to generate the metagene?

Thank you!

**Comment by lundlab-kaltinel** [comment]
Sure.
First, I imported my GTF file as a GRangesList object, then used `metagene.new` function followed by` produce metagene`. 
```
regions <- gffReadGR("/path/to/my/ensembl.gtf")

mgtwo <- metagene2$new(regions = regions, 
                   bam_files = bam_files, 
                   assay='rnaseq')

mgtwo$produce_metagene(region_names="ENST00000000412" ,title = "Demo metagene plot ENST00000000412 ")
```

**Comment by ericfournier2** [comment]
Hello lundlab-kaltinel,

by default, when working with rnaseq, metagene splits all genes into separate region groups. You can override this behaviour by specifying your own region metadata, and telling metagene on which metadata column you want regions to be split.

```
# Generate a test metagene using the demo RNA-seq data.
test = metagene2$new(regions=get_demo_rna_regions(), bam_files=get_demo_rna_bam_files(), assay="rnaseq")

# By default, if we plot the metagene now, all genes will be split independantly.
test$produce_metagene()
```
![image](https://user-images.githubusercontent.com/6945390/70203437-f3ffb000-16ea-11ea-914f-f32fbff05848.png)

```
# If you want to group ALL genes together, just add a metadata column where all genes share the same value.
test$replace_region_metadata(cbind(test$get_regions_metadata(), region_group="All"))

# Now, we split the regions according to that new uniform metadata column.
test$produce_metagene(split_by="region_group")
```
![image](https://user-images.githubusercontent.com/6945390/70203538-37f2b500-16eb-11ea-832e-ee5a5447fa5b.png)

**Comment by lundlab-kaltinel** [comment]
Hi @ericfournier2 ,

Thank you for your nice explanation. It helped us and we can plot the figures now!

However, I realized that we are grouping the exons together in 'rnaseq' mode. Is it possible for us to merge CDSs instead for exons for all transcripts? If we were to generate a CDS metagene for transcripts?

**Comment by ericfournier2** [comment]
Hello @lundlab-kaltinel ,

metagene2 does not know or care if the regions you pass it are exons, CDSs or parts of a superenhancer. If you want to plot CDSes, you must filter them upstream when you create your regions object.

An example of how to do this using ENSEMBL's yeast reference gff:

```
full_gff = rtracklayer::import("input/Saccharomyces_cerevisiae.R64-1-1.95.gff3")
cds_only = full_gff [full_gff $type=="CDS"]
CDS_by_gene = split(cds_only , by=cds_only$ID)
CDS_by_gene = GRangesList(CDS_by_gene)
```

You might have to adjust dependingon the exact structure and extra columns from your gff file.

Hope this helps!

**Comment by lundlab-kaltinel** [comment]
Thank you very much! Works well now.
