### ISSUE TITLE
Issues in producing Metagene plot

### ISSUE THREAD

**Issue by chrmarinaccio** [ArnaudDroitLab/metagene2#28]
Dear Developers,
I am just beginning to learn how to perform metagene analysis and I found your package which had a very detailed tutorial. I have ChIP-seq data for RNA Pol II which should have strong binding at active gene promoters across all genome. After alignments on hg19 I sorted the BAM files by coordinate and indexed them (I use sambamba to do that, not samtools).
To test the package I took 2 of my BAM files and indexes and then generated common ranges using all the hg19 TSS (promoter regions +/- 2kb) using the example in the tutorial. I was able to run metagene$new only by using force_seqlevels = TRUE, but after that I could not produce the metagene plot and ended up with this error:

Error in (function (classes, fdef, mtable)  : 
  unable to find an inherited method for function ‘Views’ for signature ‘"NULL"’ 

An issue regarding the same error was opened a while ago in the CharlesJB/metagene branch and the answer to that issue was that the message comes up when no reads are in the promoter regions. It does not seem to be my case because when I visualize my BAM files in IGV along with H3K4me3 data that marks active promoters I clearly see peaks for RNA Pol II in the same regions. This tells me the reads are there, but I am not sure why metagene2 is not plotting them.
Any thoughts on how I can solve the problem, or what could be wrong with the BAM files I give metagene2?

Thanks a lot for your time!
Christian

**Comment by ericfournier2** [comment]
Are you certain that your BAM files and promoter regions are using the same coordinate system? This sounds like an issue of mismatched chromosome names: chr1 vs 1, for example.

**Comment by chrmarinaccio** [comment]
> Are you certain that your BAM files and promoter regions are using the same coordinate system? This sounds like an issue of mismatched chromosome names: chr1 vs 1, for example.

Yes that was also mentioned in the other issue. I checked that with seqlevelsStyle(Rsamtools::BamFile() and it was "UCSC" so chr1. I got the regions from TxDb.Hsapiens.UCSC.hg19.knownGene and those ones should have the UCSC convention if I am not mistaken

**Comment by ericfournier2** [comment]
Would it be possible to have your analysis script and a subset of your bam files, please?

**Comment by chrmarinaccio** [comment]
Hi Eric,
Sure, I'm attaching a subset of the two .bam files. I did not do the alignment for these files, but I suppose they have been aligned with bowtie as it is ChIP-seq data. Then I simply sorted them by coordinate and indexed them in a standard way.
The rest of the analysis is basically the same as the tutorial:

all_gene_bodies = GenomicFeatures::genes(TxDb.Hsapiens.UCSC.hg19.knownGene) # Retrieve coordinates of all gene bodies in the genome
all_TSS = GenomicFeatures::promoters(all_gene_bodies, upstream=2000, downstream=2000) # Retrieve all promoter regions, with a window of 2kb upstream and 2kb downstream one per transcript of coding genes
bam_files <- c("/xxxx.bam", "/yyyy.bam") # paths of BAM files

mg <- metagene2$new(regions = all_TSS, bam_files = bam_files, assay = 'chipseq', force_seqlevels = TRUE)
mg$produce_metagene()

I tried to use plotprofile in deeptools and that approach worked, but still I am curious to understand what I am doing wrong in metagene2.

[Subsets.zip](https://github.com/ArnaudDroitLab/metagene2/files/4095925/Subsets.zip)

**Comment by ericfournier2** [comment]
Hi,

I've looked at your bam fils, and they do use the same sequence levels as those generated for your promoter regions. Your code fails with the provided bam subsets, but that's because your BAM files are sorted so by keeping only the head, you kept only reads at the start of chrM, and mitochondrial promoters are not included in the TxDb.Hsapiens.UCSC.hg19.knownGene database.

By using an appropriate mitochondrial region:
```
chrM_region=GRanges("chrM:300-400")
```
the metagenes are generated successfully.

Are your bam files limited to chrM, or something similar? As you figured out from the other issue, this error occurs when there are no reads in the provided regions, so we ned to figure out what's causing this mismatch, given that the promoter regions are "normal" as far as I can tell.

If you provide me with the full bam files, I can have another look.

**Comment by chrmarinaccio** [comment]
No they are not limited. The BAM files have been aligned to hg19 so it is aligned on all the genome. Probably it is better as you said to have a look at all the BAM file. The reads are present in the promoter regions, I am pretty sure of that because I also looked at the IGV tracks of the BAM files in combination with a BED file for promoter regions that I generated from TxDb.Hsapiens.UCSC.hg19.knownGene.

I can send you one full BAM files but not here, it is a 2gb file so can I ask you your contact to send it over?

**Comment by ericfournier2** [comment]
My email is ericfournier2 at yahoo.ca, but I don't think my email inbox will accept 2Gb files, but maybe put it on dropbox or google drive somewhere?

**Comment by mj163163** [comment]
What's the solution? I also have the same errors.
Where to use the following code?
chrM_region=GRanges("chrM:300-400")

**Comment by ericfournier2** [comment]
Hello @mj163163 ,

I would need a lot more details to help you with your problem. Could you open a new issue and give more details there? What are you trying to do, what are your BAM files, what code are you using, etc.?

**Comment by mj163163** [comment]
@ericfournier2 Thank you for the reply. I am doing all the same analysis using H19 as @chrmarinaccio.  I have the exact same error and your answer will solve the problem (chrM, and mitochondrial promoters are not included in the TxDb.Hsapiens.UCSC.hg19.knownGene database). It works if using **chrM_region=GRanges("chrM:300-400")**. So I wonder how to add chrM to the all_TSS region to solve the problem?
Thanks.

**Comment by ericfournier2** [comment]
You can concatenante GRanges object using the concatenating operator c(). So:

chrM_region=GRanges("chrM:300-400")
with_chrM = c(all_TSS, chrM_region)

will give you a with_chrM object which will contain the specified regions.
