### ISSUE TITLE
Error while plotting metagene plot

### ISSUE THREAD

**Issue by anksi** [ArnaudDroitLab/metagene2#29]
Hi Support team,
I am trying to plot the metagene plot on my Chip-seq data. I am running my jobs on HPC with below-mentioned resources. My *.bam files are huge 2.2Gb - 4.7 Gb and because of the same reason, I was getting "Error: cannot allocate vector of size". 

**Attempt 1**
1)To resolve the same, I have chunked my bam files, "x" Gb to ~250 Mb, still the error persists.
     
Warning messages:
1: In .make_GAlignmentPairs_from_GAlignments(gal, strandMode = strandMode,  :
    150 alignments with ambiguous pairing were dumped.
    Use 'getDumpedAlignments()' to retrieve them from the dump environment.
2: In .make_GAlignmentPairs_from_GAlignments(gal, strandMode = strandMode,  :
    201 alignments with ambiguous pairing were dumped.
    Use 'getDumpedAlignments()' to retrieve them from the dump environment.
Error: cannot allocate vector of size 61.6 Gb
Execution halted

**Attempt 2**
2) Instead of giving entire mm9.known.gene.bed file as a region, when I have given subsection of the *.bed (only chr5) as a region, with ~250 Mb bam file, it runs without any error but gives a blank plot. Am I missing something?

**Code used**
annots = c('mm9_basicgenes')
annotations = build_annotations(genome = 'mm9', annotations = annots)
regions = readBed("/mouse/mm9.knownGene.bed",track.line=FALSE,remove.unusual=FALSE)
BamFile_control_m6A_new2 <- c("try0.bam", "try1.bam")
dm_annotated = annotate_regions(regions = regions, annotations = annotations, ignore.strand = TRUE, quiet = FALSE)
mg <- metagene2$new(regions = dm_annotated, bam_files = BamFile_control_m6A_new2, padding_size = 0, cores = SerialParam(), verbose = FALSE, force_seqlevels = FALSE, assay = "chipseq", paired_end = TRUE, region_mode="auto", bin_count = 1)
mg$plot(title = "m6A Demo metagene plot")

Any suggestion would be much appreciated!

**HPC resource setting**
#SBATCH --mem-per-cpu 90G
#SBATCH -c 10
#SBATCH -t 72:0:0
#limit vmemoryuse 4096m
#ulimit -t 600 -v 4000000
#memory.size(max = TRUE)
#memory.limit(size = NA)
 
**Environment info**
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
_r-mutex                  1.0.1               anacondar_1    conda-forge
attrs                     19.3.0                     py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
binutils_impl_linux-64    2.34                 h53a641e_2    conda-forge
binutils_linux-64         2.34                hc952b39_20    conda-forge
bioconductor-annotate     1.66.0                    r40_0    bioconda
bioconductor-annotationdbi 1.50.0                    r40_0    bioconda
bioconductor-annotationhub 2.20.0                    r40_0    bioconda
bioconductor-annotatr     1.14.0                    r40_0    bioconda
bioconductor-biobase      2.48.0            r40h037d062_0    bioconda
bioconductor-biocfilecache 1.12.0                    r40_0    bioconda
bioconductor-biocgenerics 0.34.0                    r40_0    bioconda
bioconductor-biocparallel 1.22.0            r40h5f743cb_0    bioconda
bioconductor-biocversion  3.11.1                    r40_0    bioconda
bioconductor-biomart      2.44.0                    r40_0    bioconda
bioconductor-biostrings   2.56.0            r40h037d062_0    bioconda
bioconductor-bsgenome     1.56.0                    r40_0    bioconda
bioconductor-dbchip       1.32.0                    r40_0    bioconda
bioconductor-delayedarray 0.14.0            r40h037d062_0    bioconda
bioconductor-deseq        1.39.0            r40h037d062_0    bioconda
bioconductor-edger        3.30.0            r40h5f743cb_0    bioconda
bioconductor-genefilter   1.70.0            r40hc6cf775_0    bioconda
bioconductor-geneplotter  1.66.0                    r40_0    bioconda
bioconductor-genomation   1.20.0            r40h5f743cb_0    bioconda
bioconductor-genomeinfodb 1.24.0                    r40_0    bioconda
bioconductor-genomeinfodbdata 1.2.3                     r40_0    bioconda
bioconductor-genomicalignments 1.24.0            r40h037d062_0    bioconda
bioconductor-genomicfeatures 1.40.0                    r40_0    bioconda
bioconductor-genomicranges 1.40.0            r40h037d062_0    bioconda
bioconductor-impute       1.62.0            r40h323e27b_0    bioconda
bioconductor-interactivedisplaybase 1.26.0                    r40_0    bioconda
bioconductor-iranges      2.22.1            r40h037d062_0    bioconda
bioconductor-limma        3.44.1            r40h037d062_0    bioconda
bioconductor-metagene2    1.4.0                     r40_0    bioconda
bioconductor-regioner     1.20.0                    r40_0    bioconda
bioconductor-rhtslib      1.20.0            r40h037d062_0    bioconda
bioconductor-rsamtools    2.4.0             r40h5f743cb_0    bioconda
bioconductor-rtracklayer  1.48.0            r40h037d062_0    bioconda
bioconductor-s4vectors    0.26.0            r40h037d062_0    bioconda
bioconductor-seqpattern   1.20.0                    r40_0    bioconda
bioconductor-summarizedexperiment 1.18.1                    r40_0    bioconda
bioconductor-xvector      0.28.0            r40h037d062_0    bioconda
bioconductor-zlibbioc     1.34.0            r40h037d062_0    bioconda
bleach                    3.1.5              pyh9f0ad1d_0    conda-forge
bwidget                   1.9.14                        0    conda-forge
bzip2                     1.0.8                h516909a_2    conda-forge
ca-certificates           2020.4.5.1           hecc5488_0    conda-forge
cairo                     1.16.0            hcf35c78_1003    conda-forge
certifi                   2020.4.5.1       py37hc8dfbb8_0    conda-forge
curl                      7.69.1               h33f0ec9_0    conda-forge
decorator                 4.4.2                      py_0    conda-forge
defusedxml                0.6.0                      py_0    conda-forge
entrypoints               0.3             py37hc8dfbb8_1001    conda-forge
fontconfig                2.13.1            h86ecdb6_1001    conda-forge
freetype                  2.10.2               he06d7ca_0    conda-forge
fribidi                   1.0.9                h516909a_0    conda-forge
gcc_impl_linux-64         7.5.0                hd420e75_6    conda-forge
gcc_linux-64              7.5.0               h09487f9_20    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
gfortran_impl_linux-64    7.5.0                hdf63c60_6    conda-forge
gfortran_linux-64         7.5.0               h09487f9_20    conda-forge
glib                      2.64.3               h6f030ca_0    conda-forge
graphite2                 1.3.13            he1b5a44_1001    conda-forge
gsl                       2.6                  h294904e_0    conda-forge
gxx_impl_linux-64         7.5.0                hdf63c60_6    conda-forge
gxx_linux-64              7.5.0               h09487f9_20    conda-forge
harfbuzz                  2.4.0                h9f30f68_3    conda-forge
icu                       64.2                 he1b5a44_1    conda-forge
importlib-metadata        1.6.0            py37hc8dfbb8_0    conda-forge
importlib_metadata        1.6.0                         0    conda-forge
ipykernel                 5.3.0            py37h43977f1_0    conda-forge
ipython                   7.14.0           py37hc8dfbb8_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
jedi                      0.17.0           py37hc8dfbb8_0    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.2.0            py37hc8dfbb8_1    conda-forge
jupyter_client            6.1.3                      py_0    conda-forge
jupyter_core              4.6.3            py37hc8dfbb8_1    conda-forge
krb5                      1.17.1               h2fd8d38_0    conda-forge
ld_impl_linux-64          2.34                 h53a641e_2    conda-forge
libblas                   3.8.0               16_openblas    conda-forge
libcblas                  3.8.0               16_openblas    conda-forge
libcurl                   7.69.1               hf7181ac_0    conda-forge
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1007    conda-forge
libgcc-ng                 9.2.0                h24d8f2e_2    conda-forge
libgfortran-ng            7.5.0                hdf63c60_6    conda-forge
libgomp                   9.2.0                h24d8f2e_2    conda-forge
libiconv                  1.15              h516909a_1006    conda-forge
liblapack                 3.8.0               16_openblas    conda-forge
libopenblas               0.3.9                h5ec1e0e_0    conda-forge
libpng                    1.6.37               hed695b0_1    conda-forge
libsodium                 1.0.17               h516909a_0    conda-forge
libssh2                   1.9.0                hab1572f_2    conda-forge
libstdcxx-ng              9.2.0                hdf63c60_2    conda-forge
libtiff                   4.1.0                hc7e4089_6    conda-forge
libuuid                   2.32.1            h14c3975_1000    conda-forge
libwebp-base              1.1.0                h516909a_3    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.10               hee79883_0    conda-forge
llvm-openmp               10.0.0               hc9558a2_0    conda-forge
lz4-c                     1.9.2                he1b5a44_1    conda-forge
make                      4.3                  h516909a_0    conda-forge
markupsafe                1.1.1            py37h8f50634_1    conda-forge
mistune                   0.8.4           py37h8f50634_1001    conda-forge
nbconvert                 5.6.1            py37hc8dfbb8_1    conda-forge
nbformat                  5.0.6                      py_0    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
notebook                  6.0.3            py37hc8dfbb8_0    conda-forge
openssl                   1.1.1g               h516909a_0    conda-forge
packaging                 20.4               pyh9f0ad1d_0    conda-forge
pandoc                    2.9.2.1                       0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
pango                     1.42.4               h7062337_4    conda-forge
parso                     0.7.0              pyh9f0ad1d_0    conda-forge
pcre                      8.44                 he1b5a44_0    conda-forge
pcre2                     10.34                h2f06484_0    conda-forge
pexpect                   4.8.0            py37hc8dfbb8_1    conda-forge
pickleshare               0.7.5           py37hc8dfbb8_1001    conda-forge
pip                       20.1.1             pyh9f0ad1d_0    conda-forge
pixman                    0.38.0            h516909a_1003    conda-forge
prometheus_client         0.8.0              pyh9f0ad1d_0    conda-forge
prompt-toolkit            3.0.5                      py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pygments                  2.6.1                      py_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.16.0           py37h8f50634_0    conda-forge
python                    3.7.6           h8356626_5_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pyzmq                     19.0.1           py37hac76be4_0    conda-forge
r-askpass                 1.1               r40hcdcec82_2    conda-forge
r-assertthat              0.2.1             r40h6115d3f_2    conda-forge
r-backports               1.1.7             r40hcdcec82_0    conda-forge
r-base                    4.0.0                hdca8982_3    conda-forge
r-base64enc               0.1_3           r40hcdcec82_1004    conda-forge
r-bh                      1.72.0_3          r40h6115d3f_1    conda-forge
r-biocmanager             1.30.10           r40h6115d3f_1    conda-forge
r-bit                     1.1_15.2          r40hcdcec82_1    conda-forge
r-bit64                   0.9_7           r40hcdcec82_1002    conda-forge
r-bitops                  1.0_6           r40hcdcec82_1004    conda-forge
r-blob                    1.2.1             r40h6115d3f_1    conda-forge
r-boot                    1.3_25            r40h6115d3f_1    conda-forge
r-brew                    1.0_6           r40h6115d3f_1003    conda-forge
r-broom                   0.5.6             r40h6115d3f_1    conda-forge
r-callr                   3.4.3             r40h6115d3f_1    conda-forge
r-caret                   6.0_86            r40hcdcec82_2    conda-forge
r-cellranger              1.1.0           r40h6115d3f_1003    conda-forge
r-class                   7.3_17            r40hcdcec82_1    conda-forge
r-cli                     2.0.2             r40h6115d3f_1    conda-forge
r-clipr                   0.7.0             r40h6115d3f_1    conda-forge
r-cluster                 2.1.0             r40h9bbef5b_3    conda-forge
r-codetools               0.2_16          r40h6115d3f_1002    conda-forge
r-colorspace              1.4_1             r40hcdcec82_2    conda-forge
r-commonmark              1.7             r40hcdcec82_1002    conda-forge
r-covr                    3.5.0             r40h0357c0b_1    conda-forge
r-crayon                  1.3.4           r40h6115d3f_1003    conda-forge
r-crosstalk               1.1.0.1           r40h6115d3f_1    conda-forge
r-curl                    4.3               r40hcdcec82_1    conda-forge
r-data.table              1.12.8            r40hcdcec82_1    conda-forge
r-dbi                     1.1.0             r40h6115d3f_1    conda-forge
r-dbplyr                  1.4.3             r40h6115d3f_1    conda-forge
r-desc                    1.2.0           r40h6115d3f_1003    conda-forge
r-devtools                2.3.0             r40h6115d3f_1    conda-forge
r-digest                  0.6.25            r40h0357c0b_2    conda-forge
r-dplyr                   0.8.5             r40h0357c0b_1    conda-forge
r-dt                      0.13              r40h6115d3f_1    conda-forge
r-ellipsis                0.3.1             r40hcdcec82_0    conda-forge
r-essentials              4.0                    r40_2002    conda-forge
r-evaluate                0.14              r40h6115d3f_2    conda-forge
r-fansi                   0.4.1             r40hcdcec82_1    conda-forge
r-farver                  2.0.3             r40h0357c0b_1    conda-forge
r-fastmap                 1.0.1             r40h0357c0b_1    conda-forge
r-forcats                 0.5.0             r40h6115d3f_1    conda-forge
r-foreach                 1.5.0             r40h6115d3f_1    conda-forge
r-foreign                 0.8_80            r40hcdcec82_0    conda-forge
r-formatr                 1.7               r40h6115d3f_2    conda-forge
r-fs                      1.4.1             r40h0357c0b_1    conda-forge
r-futile.logger           1.4.3           r40h6115d3f_1003    conda-forge
r-futile.options          1.0.1           r40h6115d3f_1002    conda-forge
r-generics                0.0.2           r40h6115d3f_1003    conda-forge
r-ggplot2                 3.3.0             r40h6115d3f_1    conda-forge
r-gh                      1.1.0             r40h6115d3f_1    conda-forge
r-gistr                   0.5.0             r40h6115d3f_1    conda-forge
r-git2r                   0.27.1            r40h7253d3a_0    conda-forge
r-glmnet                  4.0               r40h9bbef5b_0    conda-forge
r-glue                    1.4.1             r40hcdcec82_0    conda-forge
r-gower                   0.2.1             r40hcdcec82_2    conda-forge
r-gridbase                0.4_7           r40h6115d3f_1003    conda-forge
r-gtable                  0.3.0             r40h6115d3f_3    conda-forge
r-haven                   2.3.0             r40hde08347_0    conda-forge
r-hexbin                  1.28.1            r40h9bbef5b_1    conda-forge
r-highr                   0.8               r40h6115d3f_2    conda-forge
r-hms                     0.5.3             r40h6115d3f_1    conda-forge
r-htmltools               0.4.0             r40h0357c0b_1    conda-forge
r-htmlwidgets             1.5.1             r40h6115d3f_1    conda-forge
r-httpuv                  1.5.2             r40h0357c0b_2    conda-forge
r-httr                    1.4.1             r40h6115d3f_2    conda-forge
r-ini                     0.3.1           r40h6115d3f_1003    conda-forge
r-ipred                   0.9_9             r40hcdcec82_2    conda-forge
r-irdisplay               0.7                    r40_1002    conda-forge
r-irkernel                1.1               r40h6115d3f_1    conda-forge
r-isoband                 0.2.1             r40h0357c0b_1    conda-forge
r-iterators               1.0.12            r40h6115d3f_1    conda-forge
r-jsonlite                1.6.1             r40hcdcec82_1    conda-forge
r-kernsmooth              2.23_17           r40hfa343cc_1    conda-forge
r-knitr                   1.28              r40h6115d3f_1    conda-forge
r-labeling                0.3             r40h6115d3f_1003    conda-forge
r-lambda.r                1.2.4             r40h6115d3f_1    conda-forge
r-later                   1.0.0             r40h0357c0b_1    conda-forge
r-lattice                 0.20_41           r40hcdcec82_2    conda-forge
r-lava                    1.6.7             r40h6115d3f_1    conda-forge
r-lazyeval                0.2.2             r40hcdcec82_2    conda-forge
r-lifecycle               0.2.0             r40h6115d3f_1    conda-forge
r-locfit                  1.5_9.4           r40hcdcec82_1    conda-forge
r-lubridate               1.7.8             r40h0357c0b_1    conda-forge
r-magrittr                1.5             r40h6115d3f_1003    conda-forge
r-maps                    3.3.0           r40hcdcec82_1004    conda-forge
r-markdown                1.1               r40hcdcec82_1    conda-forge
r-mass                    7.3_51.6          r40hcdcec82_2    conda-forge
r-matrix                  1.2_18            r40h7fa42b6_3    conda-forge
r-matrixstats             0.56.0            r40hcdcec82_1    conda-forge
r-memoise                 1.1.0           r40h6115d3f_1004    conda-forge
r-mgcv                    1.8_31            r40h7fa42b6_1    conda-forge
r-mime                    0.9               r40hcdcec82_1    conda-forge
r-modelmetrics            1.2.2.2           r40h0357c0b_1    conda-forge
r-modelr                  0.1.8             r40h6115d3f_0    conda-forge
r-munsell                 0.5.0           r40h6115d3f_1003    conda-forge
r-nlme                    3.1_148           r40h9bbef5b_0    conda-forge
r-nnet                    7.3_14            r40hcdcec82_1    conda-forge
r-numderiv                2016.8_1.1        r40h6115d3f_2    conda-forge
r-openssl                 1.4.1             r40he5c4762_1    conda-forge
r-pbdzmq                  0.3_3           r40h559a7a4_1003    conda-forge
r-pillar                  1.4.4             r40h6115d3f_0    conda-forge
r-pkgbuild                1.0.8             r40h6115d3f_0    conda-forge
r-pkgconfig               2.0.3             r40h6115d3f_1    conda-forge
r-pkgload                 1.0.2           r40h0357c0b_1002    conda-forge
r-plogr                   0.2.0           r40h6115d3f_1003    conda-forge
r-plotrix                 3.7_8             r40h6115d3f_1    conda-forge
r-plyr                    1.8.6             r40h0357c0b_1    conda-forge
r-praise                  1.0.0           r40h6115d3f_1004    conda-forge
r-prettyunits             1.1.1             r40h6115d3f_1    conda-forge
r-proc                    1.16.2            r40h0357c0b_1    conda-forge
r-processx                3.4.2             r40hcdcec82_1    conda-forge
r-prodlim                 2019.11.13        r40h0357c0b_1    conda-forge
r-progress                1.2.2             r40h6115d3f_2    conda-forge
r-promises                1.1.0             r40h0357c0b_1    conda-forge
r-pryr                    0.1.4           r40h0357c0b_1004    conda-forge
r-ps                      1.3.3             r40hcdcec82_0    conda-forge
r-purrr                   0.3.4             r40hcdcec82_1    conda-forge
r-quantmod                0.4.17            r40h6115d3f_1    conda-forge
r-r6                      2.4.1             r40h6115d3f_1    conda-forge
r-randomforest            4.6_14          r40h9bbef5b_1003    conda-forge
r-rappdirs                0.3.1           r40hcdcec82_1004    conda-forge
r-rbokeh                  0.5.0           r40h6115d3f_1003    conda-forge
r-rcmdcheck               1.3.3             r40h6115d3f_3    conda-forge
r-rcolorbrewer            1.1_2           r40h6115d3f_1003    conda-forge
r-rcpp                    1.0.4.6           r40h0357c0b_1    conda-forge
r-rcurl                   1.98_1.2          r40hcdcec82_1    conda-forge
r-readr                   1.3.1           r40h0357c0b_1004    conda-forge
r-readxl                  1.3.1             r40hde08347_4    conda-forge
r-recipes                 0.1.12            r40h6115d3f_1    conda-forge
r-recommended             4.0                    r40_1004    conda-forge
r-rematch                 1.0.1           r40h6115d3f_1003    conda-forge
r-rematch2                2.1.2             r40h6115d3f_1    conda-forge
r-remotes                 2.1.1             r40h6115d3f_1    conda-forge
r-repr                    1.1.0             r40h6115d3f_1    conda-forge
r-reprex                  0.3.0             r40h6115d3f_2    conda-forge
r-reshape2                1.4.4             r40h0357c0b_1    conda-forge
r-rex                     1.2.0             r40h6115d3f_1    conda-forge
r-rlang                   0.4.6             r40hcdcec82_0    conda-forge
r-rmarkdown               2.1               r40h6115d3f_1    conda-forge
r-roxygen2                7.1.0             r40h0357c0b_1    conda-forge
r-rpart                   4.1_15            r40hcdcec82_2    conda-forge
r-rprojroot               1.3_2           r40h6115d3f_1003    conda-forge
r-rsqlite                 2.2.0             r40h0357c0b_2    conda-forge
r-rstudioapi              0.11              r40h6115d3f_1    conda-forge
r-runit                   0.4.32          r40h6115d3f_1002    conda-forge
r-rversions               2.0.2             r40h6115d3f_0    conda-forge
r-rvest                   0.3.5             r40h6115d3f_1    conda-forge
r-scales                  1.1.1             r40h6115d3f_0    conda-forge
r-selectr                 0.4_2             r40h6115d3f_1    conda-forge
r-sessioninfo             1.1.1           r40h6115d3f_1002    conda-forge
r-shape                   1.4.4                  r40_1003    conda-forge
r-shiny                   1.4.0.2           r40h6115d3f_1    conda-forge
r-snow                    0.4_3           r40h6115d3f_1002    conda-forge
r-sourcetools             0.1.7           r40he1b5a44_1002    conda-forge
r-spatial                 7.3_12            r40hcdcec82_1    conda-forge
r-squarem                 2020.2            r40h6115d3f_1    conda-forge
r-stringi                 1.4.6             r40h0e574ca_2    conda-forge
r-stringr                 1.4.0             r40h6115d3f_2    conda-forge
r-survival                3.1_12            r40hcdcec82_1    conda-forge
r-sys                     3.3               r40hcdcec82_1    conda-forge
r-testthat                2.3.2             r40h0357c0b_1    conda-forge
r-tibble                  3.0.1             r40hcdcec82_1    conda-forge
r-tidyr                   1.1.0             r40h0357c0b_0    conda-forge
r-tidyselect              1.1.0             r40h6115d3f_0    conda-forge
r-tidyverse               1.3.0             r40h6115d3f_2    conda-forge
r-timedate                3043.102        r40h6115d3f_1002    conda-forge
r-tinytex                 0.23              r40h6115d3f_0    conda-forge
r-ttr                     0.23_6            r40hcdcec82_1    conda-forge
r-usethis                 1.6.1             r40h6115d3f_1    conda-forge
r-utf8                    1.1.4           r40hcdcec82_1003    conda-forge
r-uuid                    0.1_4             r40hcdcec82_1    conda-forge
r-vctrs                   0.3.0             r40hcdcec82_0    conda-forge
r-viridislite             0.3.0           r40h6115d3f_1003    conda-forge
r-whisker                 0.4               r40h6115d3f_1    conda-forge
r-withr                   2.2.0             r40h6115d3f_1    conda-forge
r-xfun                    0.14              r40h6115d3f_0    conda-forge
r-xml                     3.99_0.3          r40hcdcec82_1    conda-forge
r-xml2                    1.3.2             r40h0357c0b_1    conda-forge
r-xopen                   1.0.0           r40h6115d3f_1003    conda-forge
r-xtable                  1.8_4             r40h6115d3f_3    conda-forge
r-xts                     0.12_0            r40hcdcec82_1    conda-forge
r-yaml                    2.2.1             r40hcdcec82_1    conda-forge
r-zeallot                 0.1.0           r40h6115d3f_1002    conda-forge
r-zoo                     1.8_8             r40hcdcec82_0    conda-forge
readline                  8.0                  hf8c457e_0    conda-forge
sed                       4.7               h1bed415_1000    conda-forge
send2trash                1.5.0                      py_0    conda-forge
setuptools                46.4.0           py37hc8dfbb8_0    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
sqlite                    3.30.1               hcee41ef_0    conda-forge
sysroot_linux-64          2.12                 h3a0023d_3    conda-forge
terminado                 0.8.3            py37hc8dfbb8_1    conda-forge
testpath                  0.4.4                      py_0    conda-forge
tk                        8.6.10               hed695b0_0    conda-forge
tktable                   2.10                 h555a92e_3    conda-forge
tornado                   6.0.4            py37h8f50634_1    conda-forge
traitlets                 4.3.3            py37hc8dfbb8_1    conda-forge
wcwidth                   0.1.9              pyh9f0ad1d_0    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.34.2                     py_1    conda-forge
xorg-kbproto              1.0.7             h14c3975_1002    conda-forge
xorg-libice               1.0.10               h516909a_0    conda-forge
xorg-libsm                1.2.3             h84519dc_1000    conda-forge
xorg-libx11               1.6.9                h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xorg-libxext              1.3.4                h516909a_0    conda-forge
xorg-libxrender           0.9.10            h516909a_1002    conda-forge
xorg-renderproto          0.11.1            h14c3975_1002    conda-forge
xorg-xextproto            7.3.0             h14c3975_1002    conda-forge
xorg-xproto               7.0.31            h14c3975_1007    conda-forge
xz                        5.2.5                h516909a_0    conda-forge
zeromq                    4.3.2                he1b5a44_2    conda-forge
zipp                      3.1.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1006    conda-forge
zstd                      1.4.4                h6597ccf_3    conda-forge

**Comment by ericfournier2** [comment]
Hello anksi,

bam files of several gygabites are not uncommon and should not be an issue. Passing in bin_count=1 is probably not what you mean to do, and explains the empty plot you get: you're telling metagene2 to reduce your input regions into a single bin, so you get a single value per region, so no x-axis values to iterate over.

I'm not sure that would cause the "cannot allocate vector of size 61.6 Gb" error though. Could you possibly show me your input bed file, and if possible, your input bam files?

Cheers,
-Eric

**Comment by anksi** [comment]
Thanks, Eric for your prompt response!

Regarding bin_count, yes I totally agree with your suggestion of  either increasing the bin_count or removing it to iterate the function over the big region, but when I do not provide "bin_count=1", then I get below-mentioned error.

Error in bin_coverages_s(private$grouped_coverages, regions = private$select_regions(private$ph$get("region_filter")),  : 
  The specified bin_count (10nt) is larger than the smallest effective region (1nt).
Please make sure bin_count is >= 1

Input bed file is nothing but mm9.knownGene.bed and since input bam file is huge, I can share it with you via google drive, if you provide me your e-mail address?

**Comment by ericfournier2** [comment]
So, metagene2 takes your specified regions, and splits them into bin_count bins. However, it cannot do that if the specified regions are smaller than bin_count. That's whatÉ's happening here. You have at least 1 region with a size of 1 nucleotide, which is why you can't set bin_count higher than 1. ChIP-seq metagene plots make little sense on regions below 50 or 100 nucleotides in width.

You can share the bam file to ericfournier3 at gmail.com

**Comment by anksi** [comment]
I have shared my files over your mail, please have a look.

Also, while using **(annots = c('mm9_basicgenes')**, I get a below-mentioned error message which might mean, there are some genomic ranges in the .bam file where start position is more than the end position, but when I checked my the same in bam file manually, I could not find any such region. Hence, due you have any idea, what might be the cause of the below-mentioned error? 

Error in validObject(x) : invalid class “IRanges” object: 
    'width(x)' cannot contain negative integers
Calls: <Anonymous> ... start<- -> start<- -> .set_IRanges_start -> validObject
Execution halted

Thanks and Best
Ankita

**Comment by anksi** [comment]
> So, metagene2 takes your specified regions, and splits them into bin_count bins. However, it cannot do that if the specified regions are smaller than bin_count. That's whatÉ's happening here. You have at least 1 region with a size of 1 nucleotide, which is why you can't set bin_count higher than 1. ChIP-seq metagene plots make little sense on regions below 50 or 100 nucleotides in width.
> 
> You can share the bam file to ericfournier3 at gmail.com

How do you filter bam files with width > 40-50? Can one use bam filter? What is the width? Is it coverage within a specified region?

 Thanks and best
Ankita

**Comment by ericfournier2** [comment]
Hello anksi,

I haven't received anything. Are you sure you sent it to the right address?

You don't need to filter your bam file for width. Your bam file contains the alignments representing your ChIP fragments. From it metagene2 will compute genomic coverage over all regions of interest. Those regions of interest are what is defined in your bed file. Each entry in your bed file will be divided into bin_count bins. I gather from the name of your bed file that it reprensents all mouse genes? This is the file you need to filter. It's doubtful that a gene of width 1 or 10 is of much interest.

Cheers,
-Eric

**Comment by anksi** [comment]
Thanks a lot for the explanation Eric.
I am sure, I was understanding the same as it is explained by you, though I got confused with the error message and now that confusion is also resolved. Thank you.

Further, I have sent you my bam files just now, would be very nice if you can tell what might cause below-mentioned error. Thanks in advance.

Error in validObject(x) : invalid class “IRanges” object:
'width(x)' cannot contain negative integers
Calls: ... start<- -> start<- -> .set_IRanges_start -> validObject
Execution halted

Best 
Ankita

**Comment by ericfournier2** [comment]
Could you add the bed file to the drive, please?

**Comment by anksi** [comment]
Yes, I have added it.

**Comment by ericfournier2** [comment]
Hello Anksi,

this is not a bed file, but rather a GTF file, containing all genes, transcripts, exons, CDS, start and stop codons, coming in at over a million regions. This is most likely the cause of all of your issues.

Could you tell me more about your experimental design? What kind of data do you have, and which genomic regions are of interest to you?

**Comment by anksi** [comment]
I wanted to plot metagene plot for all of the genes across all of the regions, that's why I thought it would be good ides to convert gtf file to bed file. Though, I should admit that I have made six columns bed file as well which gives the same error.

Further, with the small bed region (for e.g. I have taken bed file belonging to entire chr5) command usually works but it never worked for "mm9_basicgenes", one of the Ranges annotation.

 Error in validObject(x) : invalid class “IRanges” object:
'width(x)' cannot contain negative integers
Calls: ... start<- -> start<- -> .set_IRanges_start -> validObject
Execution halted

thanks for your prompt response.

Best
Ankita

**Comment by ericfournier2** [comment]
metagene2 interprets each row of the bed file as a region to be aggregated. The GTF contains transcripts, CDS, exons and start/stop codons, which cannot be logically aggregated together. Also, this particular GTF doesn'T have gene coordinates, only transcripts. So I'd recommend you drop that file altogether.

If you want to get a metagene for all mm9 genes, you can do the following. It's a bit long to run, but RAM usage never topped 6GB when I ran it:
```R
library(AnnotationHub)
ah = AnnotationHub()

txdb = query(ah, "TxDb.Mmusculus.UCSC.mm9.knownGene.sqlite")[[1]]
gene_gr = genes(txdb)
gene_gr = gene_gr[width(gene_gr) >= 100]

library(metagene2)
bam_names = c("Ctrl-245-KI-input.bam", "Ctrl-232-WT-input.bam")
mg = metagene2$new(regions=gene_gr, bam_files=bam_names, assay="chipseq", cores=2)
mg$produce_metagene()
```
![image](https://user-images.githubusercontent.com/6945390/83072265-71720080-a03c-11ea-9349-47eb04c6f0cb.png)

Using whole gene bodies as regions can also lead to strange results, since most proteins do not bind uniformly over the whole gene, and heterogeneity of gene length will obscure certain binding features when aggregating (TSS/TES effects, for example, which are usually of fixed length and not relative to gene length).

**Comment by anksi** [comment]
Thanks for your detailed explanation Eric.

Best
Ankita

**Comment by jmvillalobos** [comment]
Hi Eric,

I have the same problem, I suppose it is due to the format of regions, I have a GFF file, which does not contain defined genes either. Do you have any idea how I can use this format to run mategene2? If you want, I send you my GFF file, it belongs to the Trichoderma atroviride fungus and I am evaluating a degradome-seq.

Thanks,
Manuel
