### ISSUE TITLE
Bioconductor: Maintainer email

### ISSUE THREAD

**Issue by CharlesJB** [ArnaudDroitLab/metagene2#30]
Bonjour @ericfournier2,

Nous avons reçu un courriel de Bioconductor par rapport au courriel associé à metagene2 qui ne répond plus. Quel est le courriel qu'on devrait utiliser?

A+!
Charles.

**Comment by ericfournier2** [comment]
Bonjour @CharlesJB ,

je n'ai plus accès au courriel du CHUL. Je n'ai pas pensé à mettre à jour le courriel dans la description du paquet. Je peux être contacté à ericfournier2@yahoo.ca.

Bonne journée,
-Eric
