### ISSUE TITLE
Failing on Bioconductor builders

### ISSUE THREAD

**Issue by lshep** [ArnaudDroitLab/metagene2#31]
w.  We attempted to reach out to the listed package maintainer in the DESCRIPTION of the package fournier.eric.2@crchudequebec.ulaval.ca but it was marked as undeliverable.  Please make sure the maintainer has a valid email address as this is the email we use for all correspondence.

 We understand that your package is failing because dependency package DBChIP is not available.  We have tried to reach out to the maintainer of package DBChIP who has currently been unresponsive. It is being marked as deprecated. Please update your package to not use DBChIP to avoid deprecation of your package.

**Comment by ericfournier2** [comment]
Hi! Thanks for taking the time to bring this to my attention. That email is no longer valid. I can now be contacted at ericfournier2@yahoo.ca. I'm changing the package's DESCRIPTION accordingly. I've also removed the DBChIP dependancy, and will push the changes to upstream as soon as I'm done re-running the unit tests.

**Comment by lshep** [comment]
I see the changes and that the package now builds in devel.  
http://bioconductor.org/checkResults/devel/bioc-LATEST/metagene2/

Please also push changes to the release branch
http://bioconductor.org/checkResults/release/bioc-LATEST/metagene2/

**Comment by ericfournier2** [comment]
I've pushed a fix to release, now to wait and see the issues are indeed fixed in the next nightly build.

**Comment by ericfournier2** [comment]
metagene2 now builds in both devel and release.
